name: Build and Deploy API docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Run Lint Bundle  
        run: redocly bundle -o bundle.yaml openapi/openapi.yaml && \
             redocly build-docs bundle.yaml -o index.html        
